### ISSUE TITLE
UnitWrappers nuget library depends on TaskParallelLibrary, but it's not defined in UnitWrappers.nuspec

### ISSUE THREAD

**Issue by icnocop** [OpenSharp/UnitWrappers#5]
Hi.

Thank you for UnitWrappers 0.6.4.

The UnitWrappers nuget library depends on TaskParallelLibrary, but it's not defined in UnitWrappers.nuspec.

Trying to use ilmerge on an exe assembly that references a dll that uses UnitWrappers without a reference to TaskParallelLibrary will produce the following error message:

`Unresolved assembly reference not allowed: System.Threading.`

Thank you.

**Comment by asd-and-Rizzo** [comment]
I will fix it when update wrappers with some new methods to have something to deploy onto nuget. Or I heard nuget allows to change packages directly, so fill free to request ownership and modify.

**Comment by dzmitry-lahoda** [comment]
will fix after migration to .net core
